esphome:
  name: camara-1
  friendly_name: Camara_1

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
#  encryption:
#    key: "IjDkvthhkDnqJhLpi5l2gyRk16qci9K22c2/wBQzoC4="

ota:
#  password: "ab6d1d8e9857bc056232bb54a01ffddc"

wifi:
#  ssid: !secret wifi_ssid
#  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
  #  ssid: "Camara-1 Fallback Hotspot"
  #  password: "Dpmf0cFSHCNT"

captive_portal:

esp32_camera:
  name: Camara_1
#  internal: true     #<-- set to 'false' only if you don't want to use Frigate
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 640x480
  jpeg_quality: 10
  max_framerate: 3.0fps #a 5 funciona
  idle_framerate: 0.1fps
  agc_mode: auto
  agc_gain_ceiling: 128x
  wb_mode: auto
  vertical_flip: true      #<-- you can cange this if you need
  horizontal_mirror: true  #<-- you can cange this if you need

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

switch:
  - platform: gpio
    pin: GPIO4
    name: "Flash"
